<h1 style="font-size:60px;font-weight:bold;">Data manipulations</h1>

__melt(frame[, id_vars, value_vars, var_name, ...])__

```
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': [1, 2, 3, 4],
    'C': [2.0, 4.0, 6.0, 8.0]
})

pd.melt(df, id_vars=['A'], value_vars=['B', 'C'], var_name='variable', value_name='value')
```

__pivot(data, *, columns[, index, values])__

```
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': [1, 2, 3, 4],
    'C': [2.0, 4.0, 6.0, 8.0]
})

pd.pivot(df, columns='A', index='B', values='C')
```

__pivot_table(data[, values, index, columns, ...])__

```
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': [1, 2, 3, 4],
    'C': [2.0, 4.0, 6.0, 8.0]
})

pd.pivot_table(df, values=['B', 'C'], index=['A'], aggfunc={'B': 'count', 'C': 'sum'})
```

__crosstab(index, columns[, values, rownames, ...])__

```
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': [1, 2, 3, 4],
    'C': [2, 4, 6, 8]
})

pd.crosstab(df['A'], df['B'], values=df['C'], aggfunc=np.sum)
```

__cut(x, bins[, right, labels, retbins, ...])__

```
x = [0.5, 1.5, 2.5, 3.5, 4.5]
bins = [0, 2, 4]

pd.cut(x, bins, labels=['group1', 'group2'])
```

__qcut(x, q[, labels, retbins, precision, ...])__

```
x = [0.1, 0.5, 0.6, 0.8, 0.9]
q = [0, 0.25, 0.5, 0.75, 1.0]

pd.qcut(x, q, labels=False)
```
Sure, here are the requested markdown notebooks for each method without any explanations:

__merge(left, right[, how, on, left_on, ...])__

```
left = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})
right = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})

pd.merge(left, right, on='key')
```

__merge_ordered(left, right[, on, left_on, ...])__

```
left = pd.DataFrame({
    'key': ['K0', 'K0', 'K1', 'K5'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})
right = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3', 'K4'],
    'C': ['C0', 'C1', 'C2', 'C3', 'C4'],
    'D': ['D0', 'D1', 'D2', 'D3', 'D4']
})

pd.merge_ordered(left, right, on='key')
```

__merge_asof(left, right[, on, left_on, ...])__

```
left = pd.DataFrame({
    'time': pd.to_datetime(['2000-01-01 00:00:00', '2000-01-01 00:10:00',
                            '2000-01-01 00:10:00', '2000-01-01 00:20:00']),
    'value': [1, 2, 3, 4]
})
right = pd.DataFrame({
    'time': pd.to_datetime(['2000-01-01 00:05:00', '2000-01-01 00:15:00',
                             '2000-01-01 00:25:00']),
    'price': [10, 20, 30]
})

pd.merge_asof(left, right, on='time')
```

__concat(objs, *[, axis, join, ignore_index, ...])__

```
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})
df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7']
})

pd.concat([df1, df2], ignore_index=True)
```

__get_dummies(data[, prefix, prefix_sep, ...])__

```
df = pd.DataFrame({
    'A': ['a', 'b', 'a', 'c', 'b'],
    'B': ['x', 'y', 'x', 'z', 'x']
})

pd.get_dummies(df['A'])
```

__from_dummies(data[, sep, default_category])__

```
df = pd.DataFrame({
    'A_a': [1, 0, 1, 0, 0],
    'A_b': [0, 1, 0, 0, 1],
    'B_x': [1, 0, 1, 0, 1],
    'B_y': [0, 1, 0, 0, 0],
    'B_z': [0, 0, 0, 1, 0]
})

pd.get_dummies(df)
pd.DataFrame({c.split('_')[0]: df[c] for c in df.columns}).astype(int)
```

__factorize(values[, sort, use_na_sentinel, ...])__

```
values = pd.Series(['A', 'B', 'A', 'C', 'B', 'D'])

pd.factorize(values)[0]
```

__unique(values)__

```
values = pd.Series(['A', 'B', 'A', 'C', 'B', 'D'])

pd.unique(values)
```

__lreshape(data, groups[, dropna])__

```
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar'],
    'B': [1, 2, 3, 4],
    'C': [2.0, 4.0, 6.0, 8.0],
    'D': [10, 20, 30, 40]
})

pd.lreshape(df, {'group1': ['A', 'B'], 'group2': ['C', 'D']})
```

__wide_to_long(df, stubnames, i, j[, sep, suffix])__

```
df = pd.DataFrame({
    'A_foo_1': [1, 2, 3],
    'A_bar_1': [4, 5, 6],
    'A_foo_2': [7, 8, 9],
    'A_bar_2': [10, 11, 12],
    'B_foo_1': [13, 14, 15],
    'B_bar_1': [16, 17, 18],
    'B_foo_2': [19, 20, 21],
    'B_bar_2': [22, 23, 24],
})

pd.wide_to_long(df, stubnames=['A', 'B'], i=['foo', 'bar'], j='num', sep='_', suffix='\w+')
```

<h1 style="font-size:60px;font-weight:bold;">Top-level missing data</h1>

__isna(obj)__

```
df = pd.DataFrame({
    'A': [1, 2, 3, None],
    'B': ['foo', 'bar', None, 'baz'],
    'C': [None, None, None, None]
})

df.isna()
```

__isnull(obj)__

```
df = pd.DataFrame({
    'A': [1, 2, 3, None],
    'B': ['foo', 'bar', None, 'baz'],
    'C': [None, None, None, None]
})

pd.isnull(df)
```

__notna(obj)__

```
df = pd.DataFrame({
    'A': [1, 2, 3, None],
    'B': ['foo', 'bar', None, 'baz'],
    'C': [None, None, None, None]
})

df.notna()
```

__notnull(obj)__

```
df = pd.DataFrame({
    'A': [1, 2, 3, None],
    'B': ['foo', 'bar', None, 'baz'],
    'C': [None, None, None, None]
})

pd.notnull(df)
```

<h1 style="font-size:60px;font-weight:bold;">Top-level dealing with numeric data</h1>

__to_numeric(arg[, errors, downcast, ...])__

```
s = pd.Series(['1', '2', '3.0', '-4.5'])

pd.to_numeric(s)
```

<h1 style="font-size:60px;font-weight:bold;">Top-level dealing with datetimelike data</h1>


__to_datetime(arg[, errors, dayfirst, ...])__

```
s = pd.Series(['20130101', '2013-01-01', 'Jan 01, 2013'])

pd.to_datetime(s)
```

__to_timedelta(arg[, unit, errors])__

```
s = pd.Series(['1 days', '2 days', '3 days', '4 days'])

pd.to_timedelta(s)
```

__date_range([start, end, periods, freq, tz, ...])__

```
pd.date_range(start='2022-01-01', end='2022-01-31')
```

__bdate_range([start, end, periods, freq, tz, ...])__

```
pd.bdate_range(start='2022-01-01', end='2022-01-31')
```

__period_range([start, end, periods, freq, name])__

```
pd.period_range(start='2022-01-01', end='2022-12-31', freq='M')
```
__timedelta_range([start, end, periods, freq, ...])__

```
pd.timedelta_range(start='1 day', end='2 days', freq='6H')
```

__infer_freq(index)__

```
index = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')

pd.infer_freq(index)```

<h1 style="font-size:60px;font-weight:bold;">Top-level dealing with Interval data</h1>

__interval_range([start, end, periods, freq, ...])__

```
pd.interval_range(start=0, end=5, periods=6)
```

<h1 style="font-size:60px;font-weight:bold;">Top-level evaluation</h1>

__eval(expr[, parser, engine, local_dict, ...])__

```
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

pd.eval('A + B', local_dict=df)
```

<h1 style="font-size:60px;font-weight:bold;">Hashing</h1>

__util.hash_array(vals[, encoding, hash_key, ...])__

```
arr = np.array(['foo', 'bar', 'baz'])

pd.util.hash_array(arr)
```

__util.hash_pandas_object(obj[, index, ...])__

```
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['foo', 'bar', 'baz']
})

pd.util.hash_pandas_object(df)
```